version: '2.1'

services:

  root_db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: root_db
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10

  nocodb:
    depends_on:
      root_db:
        condition: service_healthy
    image: nocodb/nocodb:0.96.4
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - nc_data:/usr/app/data
    environment:
      NC_DB: "pg://root_db:5432?u=postgres&p=password&d=root_db"

  backend1:
    image: youplala/motus-backend:latest
    restart: always
    ports:
      - "3001:3000"

  backend2:
    image: youplala/motus-backend:latest
    restart: always
    ports:
      - "3002:3000"

  backend3:
    image: youplala/motus-backend:latest
    restart: always
    ports:
      - "3003:3000"

volumes:
  db_data: {}
  nc_data: {}